POST {{$dotenv APP_BACKEND_INDICIA_URL}}/index.php/services/rest/es-samples/_search
Authorization: Bearer {{ $dotenv access_token }}

{
    "from": 0,
    "size": 100,
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "event.parent_event_id": 22542410
                    }
                }
            ]
        }
    }
}