###
# @name Identify species
POST {{$dotenv APP_BACKEND_URL}}/api-proxy/waarneming
  ?_api_proxy_uri=identify-proxy%2Fv1%2F%3Fapp_name%3Duni-jena
Authorization: Bearer {{$dotenv access_token}}
Origin: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

image = https://inaturalist-open-data.s3.amazonaws.com/photos/156517600/original.jpeg
