export default {
  UK: 'United Kingdom',
  LT: 'Lithuania',
  ES: 'Spain',
  SE: 'Sweden',
  AD: 'Andorra',
  AL: 'Albania',
  AT: 'Austria',
  BA: 'Bosnia and Herzegovina',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BY: 'Belarus',
  CH: 'Switzerland',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  ES_CA: 'Spain (Canary Islands)',
  FI: 'Finland',
  FR: 'France',
  GR: 'Greece',
  HR: 'Croatia',
  HU: 'Hungary',
  IE: 'Ireland',
  IS: 'Iceland',
  IT: 'Italy',
  JP: 'Japan',
  LI: 'Liechtenstein',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MD: 'Moldova',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  MT: 'Malta',
  NL: 'Netherlands',
  NO: 'Norway',
  PL: 'Poland',
  PT: 'Portugal',
  PT_AZ: 'Portugal (Azores)',
  PT_MA: 'Portugal (Madeira Islands)',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russian Federation',
  SI: 'Slovenia',
  SK: 'Slovakia',
  TR: 'Turkey (Europe)',
  TRA: 'Turkey (Asia)',
  UA: 'Ukraine',
  AM: 'Armenia',
  KE: 'Kenya',
  SH: 'Saint Helena',

  // special option
  ELSEWHERE: 'Elsewhere',
};
