export default {
  // disabled - under-translated (< 80%)
  'bg-BG': 'Български',
  'sr-RS': 'Cрпски',
  'cs-CZ': 'Čeština',
  'de-DE': 'Deutsch',
  en: 'English',
  'es-ES': 'Español',
  'hr-HR': 'Hrvatski',
  'it-IT': 'Italiano',
  'lt-LT': 'Lietuvių',
  'nl-NL': 'Nederlands',
  'pt-PT': 'Português',
  'ru-RU': 'Pусский',
  'sl-SI': 'Slovenščina',
  'fi-FI': 'Suomi',
  'sv-SE': 'Svenska',
  'tr-TR': 'Türkçe',
  'pl-PL': 'Polski',
  'ro-RO': 'Română',
  // 'fr-FR': 'Français',
};
